# Generated by Django 5.2.1 on 2025-05-17 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("raw_html", models.TextField(default="")),
                ("crawled_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("interests", models.CharField(max_length=255)),
                ("homepage", models.URLField(blank=True, null=True)),
                ("homepage_content", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("sent_email", models.BooleanField(default=False)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authors",
                        to="webpages.webpage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebPagePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_number", models.IntegerField()),
                ("raw_html", models.TextField()),
                ("is_done", models.BooleanField(default=False)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="webpages.webpage",
                    ),
                ),
            ],
            options={
                "unique_together": {("page", "part_number")},
            },
        ),
    ]
