# Generated by Django 5.2.1 on 2025-05-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webpages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webpage",
            name="crawled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="webpage",
            name="raw_html",
            field=models.TextField(blank=True, default=""),
        ),
    ]
