# Generated by Django 5.2.1 on 2025-05-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webpages", "0002_alter_webpage_crawled_at_alter_webpage_raw_html"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="interests",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
