# Generated by Django 5.2.1 on 2025-08-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_alter_author_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='openalex_called',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='openalex_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='orcid_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='works',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
