# Generated by Django 5.2.1 on 2025-08-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_author_openalex_called_author_openalex_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='openalex_retries',
            field=models.IntegerField(default=0),
        ),
    ]
