# Generated by Django 5.2.1 on 2025-08-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_author_openalex_retries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='url',
            field=models.URLField(),
        ),
    ]
