# Generated by Django 5.2.1 on 2025-08-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_alter_webpage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='suggested_email',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='suggested_email_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
