# Generated by Django 5.2.1 on 2025-08-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_author_suggested_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notified_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='notified_found',
            field=models.BooleanField(default=False),
        ),
    ]
